export enum DocumentType {

    BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
    EXAM_CERTIFICATE = 'EXAM_CERTIFICATE',
    RESIDENCE_CERTIFICATE = 'RESIDENCE_CERTIFICATE',
    KITA_CERTIFICATE = 'KITA_CERTIFICATE',
    BOOK = 'BOOK',
    SCRIPT = 'SCRIPT',
    COURSE_MATERIAL = 'COURSE_MATERIAL',
    PROFILE_PICTURE = 'PROFILE_PICTURE',
    OTHER_DOCUMENT = 'OTHER_DOCUMENT',
}
